### ISSUE TITLE
3d object problem

### ISSUE THREAD

**Issue by ErdemYlm** [ibaiGorordo/IWR1443-Read-Data-Python#4] opened 2019-09-25 09:20 UTC
when i load 3d object config file it does not run. It loads the config file but it can not get the any object data. i use sdk 2

**Comment by ibaiGorordo** [comment] 2019-09-25 11:01
Hi,

I think the problem is that in since SDK 2 they changed slightly the header data. I have uploaded the program, uncomment the lines 187 and 188 and let me now if works.

If it does not work, could you tell me more about the problem?

- Does any error appear?
- Does the LED in the board turn ON when you send the configuration file?
- Make a print of byteVec and copy it here so I can check if the data is being parsing correctly.

Also, I have to mention that the plot is only going to display the data in 2D, if you want 3D display check the pyqtgraph library for 3D scatter plot.

Best regards,
Ibai

**Comment by ErdemYlm** [comment] 2019-09-25 11:21
Thank you for your answer i'll try and let you know.

**Comment by ErdemYlm** [comment] 2019-09-25 11:49
It works fine. Thank you for your support. I tried zone occupancy detection lab chirp file and it seems ok.

**Comment by ibaiGorordo** [comment] 2019-09-25 12:49
I am glad to hear that. Yeah, the zone occupancy detection uses the MMWAVE SDK demo so it should be fine.

I close this issue, let me know if you find some problem.

Best regards,
Ibai

**Closed as completed by ibaiGorordo** 2019-09-25 12:49 UTC
